

#         Powered by TabooLib 6.0         #


debug: false
metrics: true
api:
  path: "uniauth"
  key: "123456"
login:
  timeout: 120
  server: ""
  #  # 0 = 不使用Authme，强制使用扫码注册和登录
  #  # 1 = 可用Authme注册登录，也可使用扫码注册和登录
  #  mode: 0
  command-whitelist: [ ]
  # - ''
  player-name-regex: ""
  movement-range: 0
  chat: false
  blind: false # 记得恢复
commands:
  first-join: []
  join: []
  prompt: []
  scan: []
  confirm: []
  cancel: []
