

#         Powered by TabooLib 6.0         #


debug: false
metrics: true
api:
  path: "uniauth"
  key: "123456"
login:
  timeout: 120 # 秒
  session: 120 # 秒
  message-interval: 5 # 秒
  server: ""
  command-whitelist: [ ]
  # - '/spawn'
  player-name-regex: "[a-zA-Z0-9_]*"
  chat: false
  blind: true
commands:
  first-join: []
  join: []
  prompt: []
  scan: []
  confirm: []
  cancel: []
