debug: false
metrics: true
api:
  path: "uniauth"
  key: "123456"
login:
  enable: false
  server-id: "uniauth"
  # 秒
  timeout: 120
  session: true
  blind: false
  # 秒
  session-timeout: 600
  # {0}=serverid {1}=code
  qrcode-url: "https://ua.unimc.cn/mp/login?server={1}&code={0}"
  cmd: false
prometheus:
  enable: false
  pushgateway: false
  pushgateway-url: "http://localhost:9091"