

#         Powered by TabooLib 6.1         #


debug: true
metrics: true
api:
  path: "uniauth"
  key: "123456"
login:
  enable: true
  timeout: 120 # 秒
  session: true
  session-timeout: 600 # 秒
  server-id: "1"
  qrcode-url: "https://www.bing.com/search?q={0}-{1}" # {0}=code {1}=serverid